nodes = [
  { :hostname => '110', :memory => 1024, :private_ip => '192.168.1.110', :public_ip => '192.168.0.110', :forwarded_port_22 => 2210, :forwarded_port_80 => 8010, :box => 'ubuntu/focal64' },
  { :hostname => '111', :memory => 1024, :private_ip => '192.168.1.111', :public_ip => '192.168.0.111', :forwarded_port_22 => 2211, :forwarded_port_80 => 8011, :box => 'ubuntu/focal64' },
  { :hostname => '112', :memory => 1024, :private_ip => '192.168.1.112', :public_ip => '192.168.0.112', :forwarded_port_22 => 2212, :forwarded_port_80 => 8012, :box => 'ubuntu/focal64' },
]

Vagrant.configure("2") do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |nodeconfig|
			nodeconfig.vm.box = node[:box]
			# for virtualbox
			nodeconfig.vm.provider "virtualbox" do |provider|				
				provider.gui = false
				provider.name = "focal" + node[:hostname]
				provider.memory = node[:memory]
				provider.cpus = 1
				# for virtualbox
				provider.customize [
					"modifyvm", :id,
					"--cpuexecutioncap", "50"
				]
			end # provider
			nodeconfig.vm.hostname = node[:hostname]
			nodeconfig.vm.network "public_network", ip: node[:public_ip], bridged: "eno1"
			nodeconfig.vm.network "private_network", ip: node[:private_ip]
			nodeconfig.vm.network "forwarded_port", guest: 22, host: node[:forwarded_port_22]
			nodeconfig.vm.network "forwarded_port", guest: 80, host: node[:forwarded_port_80]
		end
	end
end

