Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.vm.provider "virtualbox" do |vbox|
		vbox.gui = false
		vbox.name = "Ubuntu Focal Server 64"
		vbox.memory = 4096
		vbox.cpus = 2
	end
end
