#!/bin/bash
code --install-extension aksharpatel47.vscode-flutter-helper
code --install-extension alefragnani.project-manager
code --install-extension alexisvt.flutter-snippets
code --install-extension AzMoza.aqueduct-helper
code --install-extension chiehyu.vscode-astyle
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cschlosser.doxdocgen
code --install-extension dan-c-underwood.arm
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esskar.vscode-flutter-i18n-json
code --install-extension everettjf.pubspec-dependency-search
code --install-extension felipecaputo.git-project-manager
code --install-extension FelixAngelov.bloc
code --install-extension GitHub.vscode-pull-request-github
code --install-extension gmlewis-vscode.flutter-stylizer
code --install-extension gornivv.vscode-flutter-files
code --install-extension HookyQR.beautify
code --install-extension huizhou.githd
code --install-extension ivangabriele.vscode-git-add-and-commit
code --install-extension jebbs.plantuml
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension letmaik.git-tree-compare
code --install-extension luanpotter.dart-import
code --install-extension marus25.cortex-debug
code --install-extension mhutchie.git-graph
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-iot.vscode-ros
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension vscode-icons-team.vscode-icons
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsonline.vsonline
code --install-extension oderwat.indent-rainbow
code --install-extension oscarcs.dart-syntax-highlighting-only
code --install-extension pflannery.vscode-versionlens
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension shaharkazaz.git-merger
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tonka3000.qtvsctools
code --install-extension twxs.cmake
code --install-extension uavcan.dsdl
code --install-extension waderyan.gitblame
code --install-extension ziyasal.vscode-open-in-github
code --install-extension ZixuanWang.linkerscript
code --install-extension ziyasal.vscode-open-in-github

